let g:ycm_global_ycm_extra_conf = "~/.vim/ycm_extra_conf.py"
let g:ycm_python_binary_path = 'python'
let g:ycm_confirm_extra_conf = 1

highlight Comment ctermfg=lightblue
highlight Pmenu ctermfg=15 ctermbg=0 guifg=#ffffff guibg=#000000

