# Fix terminal initialization for xterm (avoids "Aborted because of window size change")
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm*:Tc"

# Remove message display delay
set -g display-time 0

# Change prefix from ctrl-b to ctrl-a
unbind C-b
set -g prefix C-a
set -g mouse on
bind C-a send-prefix
set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
